module.exports = [ 
    { type: 'Keyword', value: 'return', range: [ 24, 29 ] },
    { type: 'JSXOpeningElement', value: '<div>', range: [ 31, 35 ] },
    { type: 'JSXOpeningElement', value: '<h1>', range: [ 36, 39 ] },
    { type: 'JSXText', value: 'Hello, World!', range: [ 40, 52 ] },
    { type: 'JSXClosingElement', value: '</h1>', range: [ 53, 57 ] },
    { type: 'JSXClosingElement', value: '</div>', range: [ 58, 63 ] },
    { type: 'Keyword', value: 'return', range: [ 94, 99 ] },
    { type: 'JSXOpeningElement',
    value: '<div>',
    range: [ 102, 106 ] },
    { type: 'JSXText', value: 'hello', range: [ 107, 111 ] },
    { type: 'JSXOpeningElement', value: '<h1>', range: [ 112, 115 ] },
    { type: 'JSXText', value: 'Hello, World!', range: [ 116, 128 ] },
    { type: 'JSXClosingElement',
    value: '</h1>',
    range: [ 129, 133 ] },
    { type: 'JSXText', value: 'world!', range: [ 134, 139 ] },
    { type: 'JSXClosingElement',
    value: '</div>',
    range: [ 140, 145 ] },
    { type: 'Keyword', value: 'return', range: [ 177, 182 ] },
    { type: 'JSXOpeningElement',
    value: '<div>',
    range: [ 191, 195 ] },
    { type: 'JSXText', value: 'hello      ', range: [ 198, 216 ] },
    { type: 'JSXOpeningElement', value: '<h1>', range: [ 217, 220 ] },
    { type: 'JSXText', value: 'Hello, World!', range: [ 221, 233 ] },
    { type: 'JSXClosingElement',
    value: '</h1>',
    range: [ 234, 238 ] },
    { type: 'JSXText', value: 'world!    ', range: [ 241, 258 ] },
    { type: 'JSXClosingElement',
    value: '</div>',
    range: [ 259, 264 ] } 
]